# Site Info
title:              "Personal"
description:        "A minimalist Jekyll theme"
author_name:        "Leo Chen" # change this to your name
logo_url:           https://leochanj105.github.io/assets/face.jfif # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://leochanj105.github.io # main url
baseurl:            ""
github_repo:        "https://github.com/leochanj105/leochanj105.github.io"
permalink:          /:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable
social_share_previews: true

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain
#theme: the-plain

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
